### ISSUE TITLE
Dude, you are fricking AWESOME

### ISSUE THREAD

**Issue by yarub123** [April-June-August/alfred-clipboard-history-archive#1]
Seriously, wow, great job on this. It's bloody brilliant. especially the searching through the backup script filter 👌. Absolutely delicious.

Thank you for your beautiful work and for sharing it with us random creatures. I am grateful to you. 

Peace be with you, brothaman. 

Edit: I'm assuming you're going to say that the clipboard.sh work was already done by someone else and you merely just added to it. NO. Yours is epic. Period. I like what you did with it. 

Edit2: The all.sqlite3 can still be searched via the "pp" script filter even if I delete the backup sqlite3 (for e.g. the 2024-06-10_23/59/25.sqlite3)?
Does all.sqlite3 update each time i invoke the clipboardarchive? or only during backup?

**Comment by April-June-August** [comment]
> Thank you for your beautiful work and for sharing it with us random creatures. I am grateful to you.

Thanks for the kind words. 😄

> The all.sqlite3 can still be searched via the "pp" script filter even if I delete the backup sqlite3 (for e.g. the 2024-06-10_23/59/25.sqlite3)?

Yes.

> Does all.sqlite3 update each time i invoke the clipboardarchive? or only during backup?

It will only be updated during a backup.

**Comment by yarub123** [comment]
Appreciate you. Thanks again.
